services:
  app:
    build: .
    container_name: laravel_octane_app
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./storage/logs:/app/storage/logs
    networks:
      - backend

networks:
  backend:
    external: true
