services:
  app:
    build: .
    container_name: laravel_octane_app
    env_file: .env.production
    environment:
      - APP_PATH=${APP_PATH}
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=false
      - OCTANE_WORKERS=${OCTANE_WORKERS:-4}
      - OCTANE_MAX_REQUESTS=${OCTANE_MAX_REQUESTS:-1000}
      - WATCH=false
    ports:
      - "8301:8001"
    volumes:
      - ./storage/logs:/app/storage/logs
    networks:
      - backend

networks:
  backend:
    external: true
